apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: fintrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: travel2024/ledger-service
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://admin:password@ledger-db:5432/ledger
          envFrom:
            - secretRef:
                name: ledger-secrets
            - configMapRef:
                 name: redis-streams-config    
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: fintrack
spec:
  selector:
    app: ledger-service
  ports:
    - port: 80
      targetPort: 8000
