apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fintrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: travel2024/transaction-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom: 
                 secretKeyRef:
                    name: transaction-service
                    key: DATABASE_URL
          envFrom:
            - secretRef:
                name: transaction-service
            - configMapRef:
                 name: redis-streams-config    
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: fintrack
spec:
  selector:
    app: transaction-service
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
    name: transaction-service
    namespace: fintrack
type: Opaque
stringData:
    DATABASE_URL: postgresql://admin:password@transaction-db:5432/transaction